"""init commit

Revision ID: 0438b669ebd5
Revises: 
Create Date: 2025-04-10 11:39:10.577136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0438b669ebd5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_clerkId', sa.String(), nullable=True),
    sa.Column('ragpicker_clerkId', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_clerkId'], ['users.clerkId'], ),
    sa.ForeignKeyConstraint(['ragpicker_clerkId'], ['users.clerkId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tips_id'), 'tips', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tips_id'), table_name='tips')
    op.drop_table('tips')
    # ### end Alembic commands ###
