"""smart contract added

Revision ID: 19abb1db3015
Revises: defaee20fde1
Create Date: 2025-04-10 19:31:10.237028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19abb1db3015'
down_revision: Union[str, None] = 'defaee20fde1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('smart_contract_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'smart_contract_address')
    # ### end Alembic commands ###
