"""changed db type to string for admin panel table

Revision ID: 914bd2e1d300
Revises: 19abb1db3015
Create Date: 2025-04-11 00:19:36.772550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '914bd2e1d300'
down_revision: Union[str, None] = '19abb1db3015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ragpicker_applications', 'status',
               existing_type=postgresql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', name='applicationstatus'),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ragpicker_applications', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', name='applicationstatus'),
               existing_nullable=True)
    # ### end Alembic commands ###
