"""init commit 2

Revision ID: defaee20fde1
Revises: 0438b669ebd5
Create Date: 2025-04-10 11:40:54.216434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'defaee20fde1'
down_revision: Union[str, None] = '0438b669ebd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tips_id', table_name='tips')
    op.drop_table('tips')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tips',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_clerkId', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ragpicker_clerkId', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_clerkId'], ['users.clerkId'], name='tips_customer_clerkId_fkey'),
    sa.ForeignKeyConstraint(['ragpicker_clerkId'], ['users.clerkId'], name='tips_ragpicker_clerkId_fkey'),
    sa.PrimaryKeyConstraint('id', name='tips_pkey')
    )
    op.create_index('ix_tips_id', 'tips', ['id'], unique=False)
    # ### end Alembic commands ###
